In [1]:
import numpy as np

In [3]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.linspace(1,10,10, dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
list(range(1,2,5))

[1]

In [11]:
np.random.randint(1,6,1)

array([2])

In [13]:
np.random.randint(31,6000,[4,3])

array([[1393, 1648, 3313],
       [4865,  277, 4835],
       [ 759, 1612,  166],
       [1282, 4160,  607]])

In [16]:
np.random.seed(54)
np.random.randint(31,6000,[4,3],)

array([[ 929, 3886, 5174],
       [3840, 3423, 2096],
       [5160, 5669, 4744],
       [3350, 4835, 3347]])

In [17]:
np.random.rand(3,4)

array([[0.6714843 , 0.02965701, 0.39156203, 0.40479404],
       [0.18963101, 0.76710564, 0.61672315, 0.92627396],
       [0.32512403, 0.25315435, 0.72021792, 0.99695746]])

In [23]:
r = np.loadtxt('somedata.txt',dtype=str)
r

array(['This', 'file', 'has', 'data', 'outside', 'the', 'python.'],
      dtype='<U7')

In [21]:
r = np.loadtxt('moredata.txt')
r

array([[45., 67., 78., 34.],
       [38., 39., 50., 67.]])

In [25]:
p = np.random.rand(3,4)
p

array([[0.19555639, 0.71252488, 0.81638996, 0.47105727],
       [0.26108617, 0.44061904, 0.20938295, 0.47290381],
       [0.23138279, 0.16117695, 0.21706215, 0.16071548]])

In [26]:
np.savetxt('new.txt',p, delimiter=',')